name: 'JS Code Analytics'
description: 'JS Code Analytics'
author: 'Koushik Kothagal'
inputs:
  milliseconds: # change this
    required: false
    description: 'input description here'
    default: '1000'
runs:
  using: 'node16'
  main: 'dist/index.js'
